### PR TITLE
fix: Added Tracking of Ticks and Optmized Exponent Calculation

### PR DESCRIPTION
**Pull request by ianlapham**

### CODE REVIEW

**Comment by vintageplayer** [comment]
Worked on this as a part of Arbitrum Hackathon and continued till the data issues are fixed. The deployed subgraph is available [here](https://thegraph.com/hosted-service/subgraph/vintageplayer/arbitrum-minimal).

v3-info repo was cloned and modified to show liquidity graph for pools in arbitrum chain. The pools had data as shown in the images:
Screenshot 2022-11-05 at 3 26 44 PM
Screenshot 2022-11-05 at 3 27 07 PM
Screenshot 2022-11-05 at 3 27 18 PM

**Comment by 1656191498** [comment]
> 作为 Arbitrum Hackathon 的一部分致力于此，并一直持续到数据问题得到解决。已部署的子图可[在此处](https://thegraph.com/hosted-service/subgraph/vintageplayer/arbitrum-minimal)获得。
> 
> v3-info repo 被克隆和修改以显示 arbitrum 链中池的流动性图。池中的数据如图所示： 屏幕截图 2022-11-05 下午 3 点 26 点 44 分 截图 2022-11-05 3 27 07 PM 截图 2022-11-05 3 27 18 PM

it still doesn't work

**Comment by vintageplayer** [comment]
> it still doesn't work

Can you please share more details? What pool? What's the issue you saw?

**Comment by 1656191498** [comment]
> 你能分享更多细节吗？什么游泳池？你看到的问题是什么？
image

**Comment by vintageplayer** [comment]
There's a different issue not related to this PR. 
Screenshot 2023-03-07 at 12 00 16 PM

The fee tier is invalid for a swap. Not sure how that's possible. @ianlapham

**Pull request merged**
